### ISSUE TITLE
Substitui Socke.io ?

### ISSUE THREAD

**Issue by GCPBigData** [loiane/reactive-spring-angular#1]
Loiane fiquei curioso com seu projeto, baixei e so comentei o inline e adicionei:

# MONGODB (MongoProperties)
spring.data.mongodb.uri=mongodb://localhost:27017/loiane_linda

depois: 

http://localhost:4200/api/orders/stream
http://localhost:4200/api/products

O resultado:
[
    {
        "id": "5f0fb6250d2b361377f2923c",
        "name": "THE",
        "description": "JIMJIBRE",
        "price": 1.58,
        "image": "http://",
        "status": "Em Estoque",
        "discounted": "Sim",
        "discount": 0.02
    },
    {
        "id": "5f0fb6340d2b361377f2923d",
        "name": "te",
        "description": "JIMJIBRE",
        "price": 1.58,
        "image": "http://",
        "status": "Em Estoque",
        "discounted": "Sim",
        "discount": 0.02
    },
    {
        "id": "5f0fb6350d2b361377f2923e",
        "name": "te",
        "description": "JIMJIBRE",
        "price": 1.58,
        "image": "http://",
        "status": "Em Estoque",
        "discounted": "Sim",
        "discount": 0.02
    },
    {
        "id": "5f0fb63b0d2b361377f2923f",
        "name": "CAFE",
        "description": "JIMJIBRE",
        "price": 1.58,
        "image": "http://",
        "status": "Em Estoque",
        "discounted": "Sim",
        "discount": 0.02
    }
]

**Comment by loiane** [comment]
:)
Em relação à pergunta, o Socket IO é um protocolo diferente, porém a forma que funciona seria um pouco semelhante, pois a conexão fica aberta até que o stream se complete.
